version: "3"
services:
  monapp:
    build: .
    image: calculatrice2023
    depends_on:
      - redis
    ports:
      - "82:82"
    networks:
      - ooredoo
    environment:
      - NOM=Ahmed CHOUCHEN
  redis:
    image: redis
    networks:
      - ooredoo

networks:
  ooredoo:
